// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

tasks.register('release', Zip) {
    archiveBaseName = "${APP_NAME}_v${VERSION_NAME}"
    destinationDirectory = file("${projectDir}")
    from rootProject.rootDir
    include '*'
    include 'gradle/**'
    include 'images/**'
    include 'app/**'
    exclude 'release'
    exclude 'build'
    exclude 'app/.externalNativeBuild'
    exclude 'app/libs'
    exclude 'app/build'
    exclude '.git'
    exclude '.gradle'
    exclude '.idea'
    exclude 'local.properties'
    exclude '*.zip'
}
